#!/bin/sh

set -e
#set -x

rm -f /etc/tomcat5/Catalina/localhost/xwiki.xml

if [ "$1" = "purge" ] && [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi

#########################
# Restart Tomcat
#########################

invoke-rc.d --quiet tomcat5 restart || {
    RESULT=$?
    # Ignore if tomcat5 init script does not exist (yet)
    if [ $RESULT != 100 ]; then
	exit $RESULT
    fi
}

#DEBHELPER#
