#!/bin/sh

set -e
#set -x

#########################
# Links
# TODO: get rid of them when jdeb add support for symbolic links
#       see https://github.com/tcurdt/jdeb/blob/master/TODO.md
#########################

## Make symlinks to centralize the webapp in tomcat6 container
ln -sf /usr/lib/xwiki /var/lib/tomcat6/webapps/xwiki

# Add MySQL connector
ln -sf /usr/share/java/mysql.jar /usr/lib/xwiki/WEB-INF/lib/

#########################
# Rights
#########################

## Make sure tomcat is able to write in the data folder
chown root.tomcat6 /var/lib/xwiki/data

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postinst.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.mysql

  dbc_mysql_createdb_encoding="UTF8"

  dbc_generate_include='template:/etc/xwiki/hibernate.cfg.xml'
  dbc_generate_include_owner='root:tomcat6'
  dbc_generate_include_perms='640'
  dbc_generate_include_args='--ucf -C\; -o template_infile=/usr/share/xwiki/templates/mysql/hibernate.cfg.xml'

  dbc_go xwiki $@
  
  ln -f /etc/xwiki/hibernate.cfg.xml /usr/lib/xwiki/WEB-INF/
fi

#########################
# Restart Tomcat
#########################

invoke-rc.d --quiet tomcat6 restart || {
    RESULT=$?
    # Ignore if tomcat6 init script does not exist (yet)
    if [ $RESULT != 100 ]; then
	exit $RESULT
    fi
}

#DEBHELPER#
