#!/bin/sh

set -e
#set -x

#########################
# Links
# TODO: get rid of them when jdeb add support for symbolic links
#       see https://github.com/tcurdt/jdeb/blob/master/TODO.md
#########################

rm -rf /etc/xwiki/lib

ln -sf /etc/xwiki/cache /usr/lib/xwiki/WEB-INF/
ln -sf /etc/xwiki/fonts /usr/lib/xwiki/WEB-INF/
ln -sf /etc/xwiki/classes /usr/lib/xwiki/WEB-INF/
ln -sf /etc/xwiki/observation /usr/lib/xwiki/WEB-INF/

# Tomcat does not support symbolic links for files
ln -f /etc/xwiki/portlet.xml /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-config.xml /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-html.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-template.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/sun-web.xml /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/web.xml /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/xwiki.properties /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-bean.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-form.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-logic.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/version.properties /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/xwiki.cfg /usr/lib/xwiki/WEB-INF/

#########################
# var
#########################

if [ ! -d /var/lib/xwiki ]; then
  mkdir -f /var/lib/xwiki
fi
if [ ! -d /var/lib/xwiki/data ]; then
  mkdir -f /var/lib/xwiki/data
fi