#!/bin/sh

set -e
#set -x

#########################
# Links
# TODO: get rid of them when jdeb add support for symbolic links
#       see https://github.com/tcurdt/jdeb/blob/master/TODO.md
#########################

# Custom tomcat context configuration
ln -sf /etc/xwiki/xwiki-tomcat.xml  /etc/tomcat5/Catalina/localhost/xwiki.xml

#########################
# Rights
#########################

## Make sure tomcat is able to write in the data folder
chown tomcat5.tomcat5 /var/lib/xwiki/data

## Give proper rights to configuration folder
chown -R tomcat5.tomcat5 /etc/xwiki

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule

#########################
# Restart Tomcat
#########################

invoke-rc.d --quiet tomcat5 restart || {
    RESULT=$?
    # Ignore if tomcat5 init script does not exist (yet)
    if [ $RESULT != 100 ]; then
	exit $RESULT
    fi
}
