#!/bin/sh

set -e
#set -x

#########################
# Links
#########################

## Make symlinks to centralize the webapp in tomcat6 container
ln -sf /usr/lib/xwiki /var/lib/tomcat6/webapps/xwiki

rm -rf /etc/xwiki/lib

ln -sf /etc/xwiki/cache /usr/lib/xwiki/WEB-INF/
ln -sf /etc/xwiki/fonts /usr/lib/xwiki/WEB-INF/
ln -sf /etc/xwiki/classes /usr/lib/xwiki/WEB-INF/
ln -sf /etc/xwiki/observation /usr/lib/xwiki/WEB-INF/

# Tomcat does not support symbolic links for files
ln -f /etc/xwiki/portlet.xml /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-config.xml /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-html.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-template.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/sun-web.xml /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/web.xml /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/xwiki.properties /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-bean.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-form.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts-logic.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/struts.tld /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/version.properties /usr/lib/xwiki/WEB-INF/
ln -f /etc/xwiki/xwiki.cfg /usr/lib/xwiki/WEB-INF/

# Add MySQL connector
ln -sf /usr/share/java/mysql.jar /usr/lib/xwiki/WEB-INF/lib/

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postinst.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.mysql

  dbc_generate_include='template:/etc/xwiki/hibernate.cfg.xml'
  dbc_generate_include_owner='root:tomcat'
  dbc_generate_include_perms='640'
  dbc_generate_include_args='--ucf -C\; -o template_infile=/usr/share/xwiki/templates/hibernate.mysql.cfg.xml.template'

  dbc_go xwiki $@
  
  ln -f /etc/xwiki/hibernate.cfg.xml /usr/lib/xwiki/WEB-INF/
fi

#########################
# Restart Tomcat
#########################

invoke-rc.d --quiet tomcat6 restart || {
    RESULT=$?
    # Ignore if tomcat6 init script does not exist (yet)
    if [ $RESULT != 100 ]; then
	exit $RESULT
    fi
}

#DEBHELPER#
