#!/bin/sh

set -e
#set -x

#########################
# Links
#########################

## Make symlinks to centralize the webapp in tomcat6 container
ln -sf /usr/lib/xwiki /var/lib/tomcat6/webapps/xwiki

# Add PostgreSQL connector
ln -sf /usr/share/java/postgresql.jar /usr/lib/xwiki/WEB-INF/lib/

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.pgsql

  dbc_generate_include='template:/etc/xwiki/hibernate.cfg.xml'
  dbc_generate_include_owner='root:tomcat6'
  dbc_generate_include_perms='640'
  dbc_generate_include_args='--ucf -C\; -o template_infile=/usr/share/xwiki/templates/hibernate.pgsql.cfg.xml.template'

  dbc_go xwiki $@
  
  ln -f /etc/xwiki/hibernate.cfg.xml /usr/lib/xwiki/WEB-INF/
fi

#########################
# Restart Tomcat
#########################

invoke-rc.d --quiet tomcat6 restart || {
    RESULT=$?
    # Ignore if tomcat6 init script does not exist (yet)
    if [ $RESULT != 100 ]; then
	exit $RESULT
    fi
}

#DEBHELPER#
