#!/bin/sh

set -e
#set -x

#########################
# Links
# TODO: get rid of them when jdeb add support for symbolic links
#       see https://github.com/tcurdt/jdeb/blob/master/TODO.md
#########################

# Add PostgreSQL connector
ln -sf /usr/share/java/postgresql.jar /usr/lib/xwiki/WEB-INF/lib/

# Custom tomcat context configuration
ln -sf /etc/xwiki/xwiki-tomcat.xml  /etc/tomcat6/Catalina/localhost/xwiki.xml

#########################
# Rights
#########################

## Make sure tomcat is able to write in the data folder
chown tomcat6.tomcat6 /var/lib/xwiki/data

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.pgsql

  dbc_generate_include='template:/etc/xwiki/hibernate.cfg.xml'
  dbc_generate_include_owner='root:tomcat6'
  dbc_generate_include_perms='640'
  dbc_generate_include_args='--ucf -C\; -o template_infile=/usr/share/xwiki/templates/pgsql/hibernate.cfg.xml'

  dbc_go xwiki $@
fi

#########################
# Restart Tomcat
#########################

invoke-rc.d --quiet tomcat6 restart || {
    RESULT=$?
    # Ignore if tomcat6 init script does not exist (yet)
    if [ $RESULT != 100 ]; then
	exit $RESULT
    fi
}

#DEBHELPER#
