#!/bin/sh

set -e
#set -x

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postinst.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.mysql

  dbc_mysql_createdb_encoding="UTF8"

  dbc_generate_include='template:/etc/xwiki/hibernate.cfg.xml'
  dbc_generate_include_perms='644'
  dbc_generate_include_args='-U -o template_infile=/usr/share/xwiki/templates/mysql/hibernate.cfg.xml'

  dbc_go xwiki $@
fi
