#!/bin/sh

set -e
#set -x

#########################
# Links
# TODO: get rid of them when jdeb add support for symbolic links
#       see https://github.com/tcurdt/jdeb/blob/master/TODO.md
#########################

# Add MySQL connector
ln -sf /usr/share/java/mysql.jar /usr/lib/xwiki/WEB-INF/lib/

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postinst.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.mysql

  dbc_mysql_createdb_encoding="UTF8"

  dbc_generate_include='template:/etc/xwiki/hibernate.cfg.xml'
  dbc_generate_include_perms='640'
  dbc_generate_include_args='-U -o template_infile=/usr/share/xwiki/templates/mysql/hibernate.cfg.xml'

  dbc_go xwiki $@
fi
