#!/bin/sh

set -e
#set -x

#########################
# Configuration
#########################

. /usr/share/debconf/confmodule
if [ -f /usr/share/dbconfig-common/dpkg/postinst.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.mysql

  extrasql=" CHARACTER SET utf8 COLLATE utf8_bin"

  dbc_generate_include='template:/etc/xwiki/hibernate.cfg.xml'
  dbc_generate_include_perms='644'
  dbc_generate_include_args='-U -o template_infile=/usr/share/xwiki/templates/mysql/hibernate.cfg.xml'

  dbc_go xwiki $@

  # Allow creating new wikis (so new databases)
  # TODO: ask it in an install step
  mysql -e "GRANT ALL PRIVILEGES ON *.* to $dbc_dbuser@'$l_dballow' IDENTIFIED BY '`dbc_mysql_escape_str $dbc_dbpass`'"
fi
