#!/bin/sh

set -e
#set -x

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
	if [ "$1" = "purge" ]; then
		db_purge
	fi
fi

if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
    . /usr/share/dbconfig-common/dpkg/postrm.mysql
    dbc_go xwiki $@
fi

# Remove hibernate configuration
if [ "$1" = "purge" ]; then
	rm -f /etc/xwiki/hibernate.cfg.xml
fi
